export enum CompanyPermissionType {
    MANAGE_COMPANY_INFORMATION = 1,
    MANAGE_COMPANY_ROLES,
    VIEW_COMPANY_ROLES,
    MANAGE_YOUR_EMPLOYEES,
    MANAGE_ALL_EMPLOYEES,
    VIEW_EMPLOYEES,
    MANAGE_YOUR_TEAMS,
    MANAGE_ALL_TEAMS,
    VIEW_TEAMS,
    VIEW_COMPANY_LOGS
}